"""add_content_hash_and_source_to_product_version

Revision ID: 2a17e29d841f
Revises: 9538030417b5
Create Date: 2025-09-22 14:32:58.518572

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2a17e29d841f'
down_revision = '9538030417b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_version', sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product_version', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_version', 'source')
    op.drop_column('product_version', 'content_hash')
    # ### end Alembic commands ###
