"""add_product_identification_fields

Revision ID: 52d4b7effb51
Revises: 8f823dc3e650
Create Date: 2025-09-22 15:57:44.359136

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '52d4b7effb51'
down_revision = '8f823dc3e650'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('retailer_product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('product_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'product_hash')
    op.drop_column('product', 'retailer_product_id')
    # ### end Alembic commands ###
