"""Make product_id optional in processing_queue

Revision ID: 9538030417b5
Revises: 3abc3b73b4a9
Create Date: 2025-09-16 12:00:29.314462

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9538030417b5'
down_revision = '3abc3b73b4a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processing_queue', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processing_queue', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
